[program:mediasoup-poc]
process_name=%(program_name)s
command=bash /home/ubuntu/workspace/mediasoup-poc/server/start.sh
directory=/home/ubuntu/workspace/mediasoup-poc/server
user=ubuntu
autostart=true
autorestart=true
startretries=3
stopwaitsecs=10
stopsignal=SIGTERM
stdout_logfile=/home/ubuntu/workspace/mediasoup-poc/server/logs/stdout.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile=/home/ubuntu/workspace/mediasoup-poc/server/logs/stderr.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=5
environment=MEDIASOUP_LISTEN_IP="0.0.0.0",PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
