apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mediasoup-poc
spec:
  ingressClassName: traefik
  rules:
    - host: liveproctoring.tpsentinel.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mediasoup-poc
                port:
                  name: http
